name: awal_kid_ipad_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dart_jsonwebtoken: ^2.14.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  go_router: ^14.6.2
  jwt_decode: ^0.3.1
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  audioplayers: ^6.1.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/lemonade/
    - assets/audio/
